id: P003044
initial_creation_type: ocr
source_metadata:
  id: bdr:W00EGS1016958
  title: རྩོམ་བྲིས་སྣ་ཚོགས་ཕྱོགས་བསྡུས་ཨུཏྤལ་གཞོན་ནུའི་ཆུན་པོ
  author: ''
  volumes:
    f234c4c86cbd489e901e72b24688df4f:
      image_group_id: I01JW215
      title: ''
      volume_number: 1
      total_pages: 130
