id: P003044
initial_creation_type: ocr
created_at: 24/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W00EGS1016958
  title: རྩོམ་བྲིས་སྣ་ཚོགས་ཕྱོགས་བསྡུས་ཨུཏྤལ་གཞོན་ནུའི་ཆུན་པོ
  author: ''
  volumes:
    f234c4c86cbd489e901e72b24688df4f:
      image_group_id: I01JW215
      title: ''
      volume_number: 1
      total_pages: 130
      base_file: v001.txt
